from __future__ import annotations

DEFAULT_DEBUG_CONTRIBUTION_RANGE_PERCENT = (0.001, 1.0)
DEFAULT_REFINEMENT_MIN_CONTRIBUTION_PERCENT = 1e-05
DEFAULT_REFINEMENT_MIN_CONTRIBUTION_DECAY = 0.995
DEPTH_RATIO_GRAD_MIN_BAND_WIDTH = 1e-4
DEFAULT_DEPTH_RATIO_GRAD_MIN = 0.0
DEFAULT_DEPTH_RATIO_GRAD_MAX = 0.1
DEFAULT_SSIM_WEIGHT = 0.05
DEFAULT_SSIM_C2 = 9e-4
DEFAULT_MAX_SCREEN_FRACTION = 0.25
DEFAULT_LR_SCHEDULE_STEPS = 30_000
DEFAULT_LR_STAGE1_STEP = 3000
DEFAULT_LR_STAGE2_STEP = 14_000

TRAINING_BUILD_ARG_DEFAULTS: dict[str, object] = {
    "base_lr": 0.002,
    "lr_pos_mul": 0.5,
    "lr_scale_mul": 15.0,
    "lr_rot_mul": 1.0,
    "lr_color_mul": 5.0,
    "lr_opacity_mul": 5.0,
    "beta1": 0.9,
    "beta2": 0.999,
    "grad_clip": 10.0,
    "grad_norm_clip": 10.0,
    "max_update": 0.05,
    "max_scale": 3.0,
    "max_anisotropy": 32.0,
    "min_opacity": 1e-4,
    "max_opacity": 0.9999,
    "position_abs_max": 1e4,
    "near": 0.1,
    "far": 120.0,
    "scale_l2_weight": 0.0,
    "scale_abs_reg_weight": 0.01,
    "sh1_reg_weight": 0.01,
    "opacity_reg_weight": 0.01,
    "density_regularizer": 0.02,
    "color_non_negative_reg": 0.01,
    "depth_ratio_weight": 0.5,
    "max_screen_fraction": DEFAULT_MAX_SCREEN_FRACTION,
    "ssim_weight": DEFAULT_SSIM_WEIGHT,
    "ssim_c2": DEFAULT_SSIM_C2,
    "refinement_loss_weight": 0.25,
    "refinement_target_edge_weight": 0.75,
    "depth_ratio_grad_min": DEFAULT_DEPTH_RATIO_GRAD_MIN,
    "depth_ratio_grad_max": DEFAULT_DEPTH_RATIO_GRAD_MAX,
    "max_allowed_density_start": 5.0,
    "max_allowed_density": 12.0,
    "position_random_step_noise_lr": 5e5,
    "position_random_step_opacity_gate_center": 0.005,
    "position_random_step_opacity_gate_sharpness": 100.0,
    "max_gaussians": 1_000_000,
    "background_mode": 1,
    "use_target_alpha_mask": False,
    "use_sh": False,
    "sh_band": 0,
    "lr_schedule_enabled": True,
    "lr_schedule_start_lr": 0.002,
    "lr_schedule_stage1_lr": 0.002,
    "lr_schedule_stage2_lr": 0.001,
    "lr_schedule_end_lr": 1.5e-4,
    "lr_schedule_steps": DEFAULT_LR_SCHEDULE_STEPS,
    "lr_schedule_stage1_step": DEFAULT_LR_STAGE1_STEP,
    "lr_schedule_stage2_step": DEFAULT_LR_STAGE2_STEP,
    "refinement_interval": 200,
    "refinement_growth_ratio": 0.04,
    "refinement_growth_start_step": 500,
    "refinement_alpha_cull_threshold": 1e-2,
    "refinement_min_contribution_percent": DEFAULT_REFINEMENT_MIN_CONTRIBUTION_PERCENT,
    "refinement_min_contribution_decay": DEFAULT_REFINEMENT_MIN_CONTRIBUTION_DECAY,
    "refinement_opacity_mul": 1.0,
    "refinement_sample_radius": 4.0,
    "lr_pos_stage1_mul": 0.1,
    "lr_pos_stage2_mul": 0.05,
    "lr_pos_stage3_mul": 0.02,
    "lr_sh_mul": 0.1,
    "lr_sh_stage1_mul": 0.1,
    "lr_sh_stage2_mul": 0.1,
    "lr_sh_stage3_mul": 0.1,
    "depth_ratio_stage1_weight": 0.03,
    "depth_ratio_stage2_weight": 0.01,
    "depth_ratio_stage3_weight": 0.001,
    "ssim_weight_stage1": 0.1,
    "ssim_weight_stage2": 0.3,
    "ssim_weight_stage3": 0.4,
    "max_screen_fraction_stage1": 0.07,
    "max_screen_fraction_stage2": 0.02,
    "max_screen_fraction_stage3": 0.007,
    "position_random_step_noise_stage1_lr": 466666.6666666667,
    "position_random_step_noise_stage2_lr": 416666.6666666667,
    "position_random_step_noise_stage3_lr": 0.0,
    "use_sh_stage1": False,
    "use_sh_stage2": True,
    "use_sh_stage3": True,
    "sh_band_stage1": 0,
    "sh_band_stage2": 2,
    "sh_band_stage3": 3,
    "train_downscale_mode": 1,
    "train_auto_start_downscale": 16,
    "train_downscale_base_iters": 200,
    "train_downscale_iter_step": 50,
    "train_downscale_max_iters": DEFAULT_LR_SCHEDULE_STEPS,
    "train_downscale_factor": 1,
    "train_subsample_factor": 0,
}
